apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software-eessi-io-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: software-eessi-io
